name: ci

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: docker/setup-qemu-action@v1
      # - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            floydocker/node-terraform-aws:latest
            floydocker/node-terraform-aws:2.2.2
